### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by aschwartz1** [WeatherVine/back_end#13]
Does this need the same response as #16 ?

https://docs.google.com/document/d/1z9lu3SoaeJHiunPm7_9ULd17AqAuMkyFqX2tMqMiVQw/edit#heading=h.5c3ny4pr1kik

Open, go to table of contents, find 'User Dashboard Page'

**Comment by Diana20920** [comment]
@aschwartz1 closing this issue since it's for the PR I merged this morning.
